name: Minimal CI Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug environment
        run: |
          echo "GitHub runner info:"
          echo "OS: $(uname -a)"
          echo "Available tools:"
          git --version
          node --version || echo "Node not available"
          npm --version || echo "NPM not available"
          yarn --version || echo "Yarn not available"
          
      - name: Manual checkout
        run: |
          mkdir -p workspace
          cd workspace
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin ${{ github.ref }}
          git checkout FETCH_HEAD
      
      - name: Install Node.js
        run: |
          cd workspace
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version
          npm --version
      
      - name: Install Yarn
        run: |
          cd workspace
          npm install -g yarn
          yarn --version
      
      - name: Install dependencies
        run: |
          cd workspace
          yarn install --frozen-lockfile
        
      - name: Compile contracts
        run: |
          cd workspace
          yarn compile || echo "Compilation failed, but continuing"
        
      - name: Basic verification
        run: |
          cd workspace
          echo "Project structure:"
          ls -la
          echo "Package info:"
          cat package.json 